name: "Gıda Terörü"
description: "Gıda sektöründeki zehir tacirlerinin ifşa edildiği platform."

permalink: /:categories/:year/:month/:day/:title:output_ext

title: "Gıda Terörü"
email: "gidadateror@gmail.com"

url: 'https://gidateroru.com' 
baseurl: ''

markdown: kramdown
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
highlighter: rouge

kramdown:
  input: GFM
  syntax_highlighter: rouge

plugins:
  - jekyll-paginate
  - jekyll-sitemap
paginate: 10
paginate_path: /page-:num

disqus-id: gidateoru
google-analytics-track-id: UA-156922937-1

source: .
destination: ./_site

sass:
    style: :compressed
    sass_dir: assets/css/

