name: "Gıda Terörü"
description: "Lightweight theme"

permalink: /:categories/:year/:month/:day/:title:output_ext

title: "Gıda Terörü"
email: gidadateror@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

url: '' 
baseurl: ''

markdown: kramdown
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
highlighter: rouge

kramdown:
  input: GFM
  syntax_highlighter: rouge

plugins:
  - jekyll-paginate
paginate: 10
paginate_path: /page-:num

#disqus-id: your-disqus-id

# Disqus
discus-identifier: atayahmet # add your discus identifier

source: .
destination: ./_site

sass:
    style: :compressed
    sass_dir: assets/css/

